### ISSUE TITLE
socket things

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#5959]
- state of patreon only sc server ?
- is ws.cables.gl cors protected? decode uses ws.cables.gl in their tutorials
- patreon only ws server ? :>

**Comment by steam0r** [comment]
- [ ] rename ws.cables.gl to socketcluster.cables.gl
- [ ] add cors list to socket.cables.gl and edit manually
- [ ] advertise on patreon

**Comment by steam0r** [comment]
ws.cables.gl is now sc.cables.gl and socket.cables.gl is free to use for every cables.gl domain, additional domains can be configured in nginx, for now...not sure if we somehow should also provide a simple websocket echo server with "channels" implementes in url-path or something `/channel1`, `/channel2`

**Comment by steam0r** [comment]
add to benefits on patreon, write on patreon channel
