### ISSUE TITLE
github links

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#6355]
op page

**Comment by vr-varad** [comment]
@pandrr Are these issues open for contributions?

**Comment by steam0r** [comment]
hey, thanks for asking, we usually mark issues as "new" and then sit down to refine on them. if you want to report a bug or request a feature, https://github.com/cables-gl/cables_docs/issues is the right repo. we will soon refine the documentation on all of this :)

**Comment by steam0r** [comment]
create endpoint that gets op-id and looks up repo by getting .json file, then, if found and would link to known and public repo, redirect

`cables.gl/op/:opId/github`

**Comment by steam0r** [comment]
this exists and redirects to github if:
- op exists
- op is core or extension op
- code is in a git repo on server/environment

will link to current branch (develop/main/master) of the checked out repo:

existing core op: https://dev.cables.gl/op/Ops.Anim.Timer_v2/github
existsing extension op: https://dev.cables.gl/op/Ops.Extension.AmmoPhysics.AmmoCharacter/github
nonexistant op: https://dev.cables.gl/op/Ops.Hammernit/github
op without public repo: https://dev.cables.gl/op/Ops.Team.Cables.MeetupTestOp/github
