### ISSUE TITLE
move userops to teams, create team for each user (with ops?)

### ISSUE THREAD

**Issue by steam0r** [cables-gl/cables#6360]

**Comment by steam0r** [comment]
- [ ] remove possibility to create userops
- [ ] create team for user when creating first "userop"
- [ ] let user decide on permissions for their "userteam"

**Comment by pandrr** [comment]
1. add Ops.Team.User_username to namespace select list
2. when using, a team is created

later:
4. remove user.xxx namespace from lists
5. add button to rename all ops to new namespace
