### ISSUE TITLE
connection errors

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#6387]
<img width="1880" alt="Screenshot 2024-08-14 at 09 28 57" src="https://github.com/user-attachments/assets/1616112d-5fe3-4dc1-ba15-86fbe2614f28">

this should not open the console, should display the connection problem icon

**Comment by steam0r** [comment]
shows icon on network errors now, does not open console (level is "warn") icon is removed on next successful "checkProjectUpdated"
