### ISSUE TITLE
spammer

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#6390]
https://cables.gl/user/n881me

https://cables.gl/user/77betazcom

**Comment by pandrr** [comment]
https://cables.gl/user/kuwinnvip

https://cables.gl/user/188bet68183

**Comment by pandrr** [comment]
https://cables.gl/user/guihangdimynhatminhexpress
https://cables.gl/user/789club98club
https://cables.gl/user/fb88luxe
https://cables.gl/user/fun88132
https://cables.gl/user/188bet68183
https://cables.gl/user/dangkyw8823

**Comment by pandrr** [comment]
<img width="1241" alt="Screenshot 2024-08-19 at 09 44 15" src="https://github.com/user-attachments/assets/5a87398f-da8d-4721-9727-d84764614d5b">

**Comment by pandrr** [comment]
only display user profile pages if they
- >0 public patches
- >0 public patches with >0 likes

show message that they need to be verified first otherwise

**Comment by steam0r** [comment]
solve this in honeypot issue
