### ISSUE TITLE
copy paste evoke jingle

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#6419]
crash...

https://dev.cables.gl/edit/YQTrBl

**Comment by steam0r** [comment]
somehow oplookup only has this in one direction:

 ~/cables/cables_api/gen (develop)> cat oplookup.json | jq | grep 78e854ac-b24a-4bb8-813e-dbdc6a721203
    "Ops.Patch.PYQTrBl.SubPatch1": "78e854ac-b24a-4bb8-813e-dbdc6a721203",
