### ISSUE TITLE
use empty image when not thumbnail exists

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#6424]

**Comment by pandrr** [comment]
<img width="896" alt="Screenshot 2024-09-04 at 13 39 09" src="https://github.com/user-attachments/assets/11bac19b-b493-43c6-8be7-87413320d8f7">

**Comment by steam0r** [comment]
how does this happen? that url sends empty images for everything unknown...

illegal id, illegal format:
https://cables.gl/thumb/hq/ILLEGAL/thumb.webp
https://cables.gl/thumb/hq/ILLEGAL/thumb.jpg

no mainloop / transparent screen, shortid, longid:
https://cables.gl/thumb/hq/lke9pn/thumb.webp
https://cables.gl/thumb/hq/66d8460395b9516098848ded/thumb.webp

no screenshot saved, shortid, longid:
https://cables.gl/thumb/hq/f0vGRn/thumb.webp
https://cables.gl/thumb/hq/66deb525e3e9c4b55a4766fb/thumb.webp

**Comment by pandrr** [comment]
hm most look fine now

https://dev.cables.gl/edit/n71lAn

this one produces a broken one ?
it even has a mainloop.......
