### ISSUE TITLE
CGL.Geometry.json2geom is not a function

### ISSUE THREAD

**Issue by steam0r** [cables-gl/cables#6470]
probably temporary because of webgpu:

https://dev.cables.gl/edit/pQpie9

![Bildschirmfoto 2024-09-12 um 15 24 43](https://github.com/user-attachments/assets/67d1da70-9308-48d1-846b-0b5381a47175)

fine on live

https://cables.gl/edit/pQpie9

**Comment by pandrr** [comment]
they now need the corelib cgl_deprecatedjson3d
