### ISSUE TITLE
export zip

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#6475]
- [x] patch export should have a different name , e.g. patch in name cables_PATCHNAME_htmlNN.zip / cables_PATCHNAME_patchNN.zip
- [x] show understandable error message if unexpected format

**Comment by steam0r** [comment]
- cables_html_ cables_patch_
- _NN.zip

**Comment by pandrr** [comment]
still is called "download"

**Comment by pandrr** [comment]
"Failed to import! Your upload contains no project files (.cables)."

- this should say how to export "export as patch"
- do not mention upload

**Comment by pandrr** [comment]
"successfully exported to: standalone"

**Comment by pandrr** [comment]
<img width="565" alt="Screenshot 2024-09-20 at 11 42 24" src="https://github.com/user-attachments/assets/b74e5276-7f8f-4868-b69f-2b7bac92cf63">

here it says the wrong name too

**Comment by steam0r** [comment]
> "Failed to import! Your upload contains no project files (.cables)."
> 
>     * [ ]  this should say how to export "export as patch"
> 
>     * [ ]  do not mention upload

not sure how to phrase this? 'Invalid format, did you export as a "patch"?'

**Comment by steam0r** [comment]
Invalid format, expected a "patch"-export.
https://cables.gl/docs/4_export_embed/dev_embed/export_standalone/export_standalone
