### ISSUE TITLE
standalone "dir" ops should (have an option to) output urls

### ISSUE THREAD

**Issue by steam0r** [cables-gl/cables#6510]
for some weird reason this works, but feels weird:

![Screenshot 2024-09-17 144002](https://github.com/user-attachments/assets/eb1ee7a5-56a0-4a90-b946-dded9c2c268f)

**Comment by steam0r** [comment]
platform paths should also be forward slashes, or urls instead of paths?

**Comment by pandrr** [comment]
urls would proabably not work with standalone file ops

**Comment by pandrr** [comment]
should not output urls, could be assetpath op or a new one

**Comment by steam0r** [comment]
yeah, i think the paths should be the paths but then we need a "path2fileurl" op: cables-gl/cables/issues/6511
