### ISSUE TITLE
op not found error

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#6553]
<img width="863" alt="Screenshot 2024-10-10 at 12 25 48" src="https://github.com/user-attachments/assets/fcf05234-3aa8-4728-b425-cb4e595c057c">

**Comment by pandrr** [comment]
- [ ] should link to editor on dev
- [ ] "you edited your patch" makes no sense, mostly happens for non patch owner

**Comment by steam0r** [comment]
show button "try dev.cables.gl"

**Comment by pandrr** [comment]
also see #6553
