### ISSUE TITLE
op not found page

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#6554]
https://cables.gl/op/75c726d6-7cc5-48e0-b4ec-7b6af6802fd9
https://dev.cables.gl/op/75c726d6-7cc5-48e0-b4ec-7b6af6802fd9

**Comment by pandrr** [comment]
<img width="1408" alt="Screenshot 2024-10-10 at 12 27 36" src="https://github.com/user-attachments/assets/5a3bd434-06bd-42fc-92b4-abb5f1092394">

this page should check and let the user know that the op exists on dev.cables.gl

maybe just a client side api request to check if that exsits on dev ?

**Comment by steam0r** [comment]
add some endpoint that checks dev via http request "in the back" so that we can add more environments eventually

**Comment by steam0r** [comment]
`/api/op/:opIdentifier/find`
