### ISSUE TITLE
remove upload file button

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#6562]
<img width="1309" alt="Screenshot 2024-10-17 at 20 00 28" src="https://github.com/user-attachments/assets/dc17c343-c6e3-4ea0-9669-a7043273eb30">

**Comment by pandrr** [comment]
instead explain to the user how to use files

**Comment by steam0r** [comment]
"Patch does not use any files, yet", "Drag files onto the patchfiled to use them"

"Project Directory" -> show path
