### ISSUE TITLE
menubar height in firefox

### ISSUE THREAD

**Issue by steam0r** [cables-gl/cables#6563]
![Bildschirmfoto 2024-10-18 um 15 10 26](https://github.com/user-attachments/assets/85db906e-1e76-4576-af30-289d5e38e9ca)

probably this, somehow:

https://github.com/cables-gl/cables_ui/commit/1133efc7e14a94d18e91824bd90225ac4cd92384

**Comment by pandrr** [comment]
firefox fuck off

**Comment by pandrr** [comment]
<img width="1951" alt="Screenshot 2024-10-18 at 15 30 21" src="https://github.com/user-attachments/assets/7f930708-645a-4a84-878a-92443f4d0021">

there is no reason why this should be 50px height
