### ISSUE TITLE
namespace 

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#6571]
<img width="847" alt="Screenshot 2024-10-21 at 12 17 18" src="https://github.com/user-attachments/assets/7917f415-810b-41f7-af40-d7a7576075ef">

- add admin lock to extension namespace
- show visibility in table as text

**Comment by steam0r** [comment]
"can be seen by everyone" ...

**Comment by steam0r** [comment]
team core namespaces should be visible "to everyone"
