### ISSUE TITLE
not all deprecated ops showing in extension ops

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#6600]
![Screenshot 2024-10-30 at 08 48 13](https://github.com/user-attachments/assets/530bb0af-fff2-421e-958c-1af48588434d)

**Comment by pandrr** [comment]
wrong

**Comment by steam0r** [comment]
left is team namespace, right is extension namespace, isnt it?

**Comment by steam0r** [comment]
ah...was closed already...

**Comment by pandrr** [comment]
yes but i think we still need one page where we can see all ops in all namespaced deprecated and not
