### ISSUE TITLE
why is it in the list if its not possible ?

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#6652]
![Screenshot 2024-11-11 at 16 57 30](https://github.com/user-attachments/assets/e9131cc4-190b-4079-90b4-5625c398b3e0)

**Comment by steam0r** [comment]
remove ops and ops.standalone, only suggest Ops.Local.

**Comment by steam0r** [comment]
removed other options from dropdown, rest is handled here: cables-gl/cables/issues/6658
