### ISSUE TITLE
duplicate attachment files

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#6690]
<img width="1058" alt="Screenshot 2024-12-02 at 09 44 56" src="https://github.com/user-attachments/assets/2314fc5b-9992-4e2c-8803-e1a0387bb32b">

**Comment by steam0r** [comment]
this._tab.addButton in tab_editor.js:136 calls adds the callback to "click", then calls `ele.asButton`, which also adds a click-listener:

```
        let html = "";
        // html += "<span class=\"icon icon-files\"></span>";
        html += title;
        button.innerHTML = html;
        button.addEventListener("click", cb);
        ele.asButton(button, cb);
```

i guess the one in `ele.asButton` is the correct one and the other one can be removed?
