### ISSUE TITLE
patch comments into community channel ?

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#6711]
i thought we had this at some point

**Comment by steam0r** [comment]
not on dev, for some reason we decided to send these messages only if the action is done on cables.gl

<img width="297" alt="Bildschirmfoto 2024-12-04 um 19 22 07" src="https://github.com/user-attachments/assets/12cd757e-9cc0-4cff-a0b7-03a6a131329c">

**Comment by pandrr** [comment]
i used it on live

**Comment by pandrr** [comment]
i used it on live

e.g. https://cables.gl/p/C6iqnt

all those comments

**Comment by pandrr** [comment]
beweise beweise
